src/main/java/examples/ListPrefix.java, src/main/java/software/amazon/nio/spi/s3/PosixLikePathRepresentation.java, src/main/java/software/amazon/nio/spi/s3/S3ClientStore.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/main/java/software/amazon/nio/spi/s3/S3Path.java, src/main/java/software/amazon/nio/spi/s3/S3ReadAheadByteChannel.java, src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java, src/main/java/software/amazon/nio/spi/s3/util/TimeOutUtils.java
Javadoc improvements and small code quality improvements
=> javadoc fixes and code quality improvements

THIRD-PARTY
#104 
Updated to include new third  party packages and versions
=> Updated versions and packages used.

README.md, src/test/java/software/amazon/nio/spi/s3x/S3PathTest.java, src/test/java/software/amazon/nio/spi/s3x/S3XFileSystemProviderTest.java, src/test/java/software/amazon/nio/spi/s3x/util/S3XFileSystemInfoTest.java
I have realized some tests haven't been merged (or pushed...) and I fixed a couple of errors in the readme
=> small corrections in readme and tests for s3x provider

src/main/java/software/amazon/nio/spi/s3/S3DirectReadableByteChannel.java, src/main/java/software/amazon/nio/spi/s3/S3ReadAheadByteChannel.java, src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java
Fixes #176
Changed logging level from `info` to `debug`.
=> Fixes #176

src/examples/resources/logback.xml
#229 
Removes chatter from the AWS SDK packages
=> add log config

src/examples/java/software/amazon/nio/spi/examples/ReadAllBytes.java
Adds an example application that uses the `Files.readAllBytes(path)` method.
=> added example of Files.readAllBytes

src/examples/java/software/amazon/nio/spi/examples/ReadAllBytes.java
Adds code body missing from last PR??
=> [chore] Added example

src/examples/java/software/amazon/nio/spi/examples/WalkFromRoot.java
Avoid unnecessary creation of a new Filesystem
=> Avoid unnecessary creation of a new Filesystem

README.md
Updates to docs. Include new section on S3 URI and W3C URI variances.
=> Updates to docs

src/examples/java/software/amazon/nio/spi/examples/CopyToS3.java
Adds an example of a cross filesystem (copy) operation
=> Adds a demo of a cross filesystem operation.

src/examples/java/software/amazon/nio/spi/examples/CopyToS3.java
#135 
Demonstrate round trip cross filesystem operations.
=> Update to show round trip

README.md
210
Document the semantics of the current behavior of `deleteIfExists`
=> explain semantics of deleteIfExists

src/examples/java/software/amazon/nio/spi/examples/ListPrefix.java
Refactor example to use a more idiomatic way to list files.
=> Refactor to use Files.list()

src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java
=> chore: remove unused constructor

src/examples/java/software/amazon/nio/spi/examples/Main.java, src/examples/java/software/amazon/nio/spi/examples/WalkFromRoot.java
Changes system out to system err for messages
=> chore: use system err for messages

src/main/java/software/amazon/nio/spi/s3/S3Path.java, src/test/java/software/amazon/nio/spi/s3/S3PathTest.java, src/test/java/software/amazon/nio/spi/s3/util/S3XFileSystemInfoTest.java
issue #237 
this PR fixes the mentioned bug, plus it cleans up S3XFileSystemInforTest
=> fix for issue #237

README.md
=> chore: re-organized testing content

src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java
Suppresses a cast warning (which is safe)
=> Suppress cast warning

src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java, src/test/java/software/amazon/nio/spi/s3/FixedS3ClientProvider.java, src/test/java/software/amazon/nio/spi/s3/S3ClientProviderTest.java
closes #314 
replaces all S3Client uses with S3AsyncClient
=> replaces all S3Client uses with S3AsyncClient

src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java
=> Make the client builder cross region.

src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java
=> Make the default client cross region.

build.gradle, src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java
Updates SDK bom and CRT together due to dependency.
=> Update aws crt and awssdk bom

README.md
=> Adds note about Amazon S3 access points

.checkstyle/suppressions.xml, build.gradle, src/examples/java/software/amazon/nio/spi/examples/ListPrefix.java, src/examples/java/software/amazon/nio/spi/examples/Main.java, src/examples/java/software/amazon/nio/spi/examples/MoveObject.java, src/examples/java/software/amazon/nio/spi/examples/ReadAllBytes.java, src/examples/java/software/amazon/nio/spi/examples/WalkFromRoot.java
#338 
removes log back SLF4J provider to reduce JAR size and make it easier for people to use their own provider.
=> chore: remove logback

build.gradle, src/test/java/software/amazon/nio/spi/s3/FakeAsyncS3ClientBuilder.java
#376 
Updates CRT and test client builder to new signature
=> fix: Updates CRT and test client builder to new signature

build.gradle, src/test/java/software/amazon/nio/spi/s3/FakeAsyncS3ClientBuilder.java
Updates bom version and adds required method to fake builder.
=> chore: updates bom version and adds implementation of new builder method

src/test/java/software/amazon/nio/spi/s3/S3PathTest.java
#293
Additional tests that should prevent regression of issue in #293 
=> tests: Additional tests for relativize.

README.md
adds downloads and license badges to README.md
=> chore: adds downloads and license badges to README.md

src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java
=> fix: prevents holding closed clients

src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java
patch: restores timeout length, perpetuates thread interruptions
=> patch: restores timeout length, perpetuates thread interruptions

build.gradle
Bump version to 2.0.2 and tag for release
=> chore: bump minor version for release

src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java, src/test/java/software/amazon/nio/spi/s3/S3ClientProviderTest.java
#435 
Removes cached clients that have been closed. Adds additional unit tests for caching logic
=> fix: fixes cache logic by removing closed clients.

README.md, build.gradle
Update dev version in `build.gradle` and `README.md`
=> chore: bump dev version.

README.md, build.gradle
=> bump version for release

.gitignore, src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/main/java/software/amazon/nio/spi/s3/config/S3NioSpiConfiguration.java, src/test/java/software/amazon/nio/spi/s3/config/S3NioSpiConfigurationTest.java
*Issue #513 :*
Added configurable timeouts for user initiated async api calls
=> Issue 513 configurable timeouts

build.gradle
=> bumps version

src/examples/java/software/amazon/nio/spi/examples/AsyncFileChannelDemo.java, src/examples/java/software/amazon/nio/spi/examples/FileChannelDemo.java, src/main/java/software/amazon/nio/spi/s3/AsyncS3FileChannel.java, src/main/java/software/amazon/nio/spi/s3/S3FileChannel.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/main/java/software/amazon/nio/spi/s3/S3WritableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3FileChannelTest.java
#481 
Adds implementation of methods `newFileChannel` and `newAsynchronousFileChannel` for `S3FileSystemProvider`
=> feature: implements newFileChannel and newAsynchronousFileChannel

README.md, build.gradle
=> bump version to 2.1.0

README.md
=> Adds feedback section

build.gradle, src/main/java/software/amazon/nio/spi/s3/S3FileChannel.java, src/main/java/software/amazon/nio/spi/s3/S3RangeHeader.java, src/test/java/software/amazon/nio/spi/s3/AsyncS3FileChannelTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileChannelTest.java, src/test/java/software/amazon/nio/spi/s3/S3OpenOptionTest.java, src/test/java/software/amazon/nio/spi/s3/S3PreventConcurrentOverwriteTest.java, src/test/java/software/amazon/nio/spi/s3/S3RangeHeaderTest.java
Improves test coverage for the worst offenders and enforces code coverage with a handful of hopefully temporary exceptions.
=> Enforce code coverage
