README.md, build.gradle, src/main/java/software/amazon/nio/spi/s3/S3ClientStore.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/main/java/software/amazon/nio/spi/s3/S3ReadAheadByteChannel.java, src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java, src/main/java/software/amazon/nio/spi/s3/S3WritableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemTest.java, src/test/java/software/amazon/nio/spi/s3/S3ReadAheadByteChannelTest.java, src/test/java/software/amazon/nio/spi/s3/S3SeekableByteChannelTest.java
**Ticket:** https://github.com/awslabs/aws-java-nio-spi-for-s3/issues/4
* This adds the NIO FileSystemProvider methods as well as a implementation of a writable channel
* With this pr the async s3 client is using now the s3 transfer manager and therefore the crt builder
=> Add NIO write operations

src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemTest.java
#35 
changed `getRootDirectories()` implementation to return a singleton list of the root `/` rather than the path itself (which is also iterable).
=> Fix for getRootDirectories()

.gitignore, THIRD-PARTY, build.gradle, src/test/java/software/amazon/nio/spi/s3/config/S3NioSpiConfigurationTest.java
*Issue #59 *
- Adding AssertJ
- Bumping java to 16 otherwise I had an error with logback
- added some more builder/IDE files to ignore
As an example of using assertj, I changed S3SpiConfigurationTest
=> Adding AssertJ (issue #59)

build.gradle, src/main/java/examples/ListPrefix.java, src/main/java/examples/WalkFromRoot.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/main/java/software/amazon/nio/spi/s3/S3Path.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java
#96 
Fixed behavior of `S3FileSystemProvider.newDirectoryStream` so that it behaves as expected.
Some example test applications are added with `examples/ListPrefix and `examples/WalkFromRoot`
=> Fixes for newDirectoryStream issues

src/main/java/software/amazon/nio/spi/s3/S3Path.java, src/test/java/software/amazon/nio/spi/s3/S3PathTest.java
=> fix for upstream/#116

build.gradle, src/main/java/software/amazon/nio/spi/s3/config/S3NioSpiConfiguration.java, src/main/java/software/amazon/nio/spi/s3/util/StringUtils.java, src/test/java/software/amazon/nio/spi/s3/config/S3NioSpiConfigurationTest.java
It also cleans up a bit the code using proper type for properties S3_SPI_READ_MAX_FRAGMENT_SIZE_PROPERTY and S3_SPI_READ_MAX_FRAGMENT_NUMBER_PROPERTY
*Issue #*
#112 
See #112 for a description of the functionality introduced.
=> Implementing fluent initialization/setting of S3NioSpiConfiguration

src/test/java/software/amazon/nio/spi/s3/config/S3NioSpiConfigurationTest.java
#131 
Clean up of S3NioSpiConfiguration
- addressing issue #131 (it was already correctly implemented, improved test)
- using assertj everywhere
=> Test code improvement and cleanup

build.gradle, src/main/java/examples/ListPrefix.java, src/main/java/examples/WalkFromRoot.java, src/main/java/software/amazon/nio/spi/s3/FixedS3ClientProvider.java, src/main/java/software/amazon/nio/spi/s3/S3BasicFileAttributes.java, src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java, src/main/java/software/amazon/nio/spi/s3/S3ClientStore.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/FakeAsyncS3ClientBuilder.java, src/test/java/software/amazon/nio/spi/s3/S3ClientProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3ClientStoreTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemTest.java, src/test/java/software/amazon/nio/spi/s3/S3PathTest.java, src/test/java/software/amazon/nio/spi/s3/S3SeekableByteChannelTest.java, src/test/java/software/amazon/nio/spi/s3/config/S3NioSpiConfigurationTest.java
#30 
As per the discussion on #30 we want to implement NIO FileSystem semantic, which is lead by the methods newFileSystem() and getFileSystem(); the former shall return a new instance or throw an exception, while the latter should return an existing instance. This means that S3FileSystem instances shall be cached (as opposed to the current implementation that caches AWSClients).
Another change introduced and discussed in other thread is the use of S3ClientProvider at S3FileSystem level in order to better decouple file system logic from the aws client creation logic (discussed in #50). This obsoletes IMHO the methods in S3FileSystemProvider that receives a AWSAsyncClient, which I would remove in future version to keep S3FileSystemProvider …
=> Addressing issue #30 about NIO FileSystem lifecycle

README.md, src/main/java/examples/WalkFromRoot.java, src/main/java/software/amazon/nio/spi/s3/FixedS3ClientProvider.java, src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java, src/main/java/software/amazon/nio/spi/s3/S3ClientStore.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/main/java/software/amazon/nio/spi/s3/S3Path.java, src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java, src/main/java/software/amazon/nio/spi/s3/config/S3NioSpiConfiguration.java, src/main/java/software/amazon/nio/spi/s3/util/S3FileSystemInfo.java, src/main/java/software/amazon/nio/spi/s3x/S3XFileSystemProvider.java, src/main/java/software/amazon/nio/spi/s3x/util/S3XFileSystemInfo.java, src/main/resources/META-INF/services/java.nio.file.spi.FileSystemProvider, src/test/java/software/amazon/nio/spi/s3/S3ClientProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3ClientStoreTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemTest.java, src/test/java/software/amazon/nio/spi/s3/S3PathTest.java, src/test/java/software/amazon/nio/spi/s3/S3ReadAheadByteChannelTest.java, src/test/java/software/amazon/nio/spi/s3/config/S3NioSpiConfigurationTest.java
This pull request should finalize the work to seamlessly support 3rd party S3 services like minio. It brings three main improvements, which I kept together as they are small enough and they complement each other.
1. All information to build a file system (bucket, endpoint, credentials, etc.) are now encapsulated in a S3NioConfiguration object that is passed to the constructor; this simplifies quite a bit the constructors and the need of accessors. This should also close #61 
2. Deprecation of constructors taking a URI: in the NIO world, the FileSystem object is usually create indirectly, by the provider or even more subtly by using Files or Path; it is therefore cleaner the provider digests the URIs creating a corresponding configuration object that can then be passed to S3FileSystem's …
=> Third party S3 services support + #61

README.md, src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java, src/main/java/software/amazon/nio/spi/s3/config/S3NioSpiConfiguration.java, src/main/java/software/amazon/nio/spi/s3x/S3XFileSystemProvider.java, src/test/java/software/amazon/nio/spi/s3/FakeAsyncS3ClientBuilder.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java, src/test/java/software/amazon/nio/spi/s3/config/S3NioSpiConfigurationTest.java, src/test/java/software/amazon/nio/spi/s3x/S3XFileSystemProviderTest.java
This PR covers issue #115 and #161 
S3 compatible services like minio do not like AWS S3 virtual-style addressing, where the bucket name is considered part of the hostname (e.g. pippo -> pippo.s3.eu-central-1.amazonaws.com).
We therefore set the path-style addressing by default for s3x provider, while we also give the possibility to configure it via the s3.spi.force-path-style.
I took this opportunity to make some improvements to the readme about the different configuration parameters. Please have a look and let me know if you like it. 
=> Fixing issues #115 and #161

src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3PathTest.java
After checking out the project and running the tests, they would fail or not depending on the order the tests are run (it is not guaranteed they are by default).
I've noticed `S3PathTest.testEquals` creates `foo` _fs_ but it is not closed; `S3FileSystemProviderTest` uses `foo` _fs_ for its tests.
So this PR introduces 2 changes:
* Cleanup _fs_ in `testEquals` after creating it
* Get or create _fs_ in `S3FileSystemProviderTest` so that it is not affected by other tests leaking resources
=> chore(test): Improve S3FileSystemProviderTest robustness

src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java
although `closeFileSystem` is removing the fs from the cache it isn't closing it explicitly. This may be causing issues in the github ci.
=> ensure FS is closed when calling closeFileSystem

src/test/java/software/amazon/nio/spi/s3/S3ClientProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemTest.java, src/test/java/software/amazon/nio/spi/s3/config/S3NioSpiConfigurationTest.java, src/test/java/software/amazon/nio/spi/s3x/S3XFileSystemProviderTest.java, src/test/java/software/amazon/nio/spi/s3x/util/S3XFileSystemInfoTest.java
This PR replaces several occurrences of the idiom:
```
try {
... // do something that throws an Exception
fail() // with some message to display because the exception should have been thrown
} catch ( someException ){
... // some assertion on the exception
}
```
with a couple of assertion methods provided by AssertJ (`assertThatCode`, `assertThatThrownBy`) and JUnit (`assertThrows`) which are already part of the dependencies of the project.
Before:
```
try {
provider.newFileSystem(URI.create(pathUri));
fail("filesystem created twice!");
} catch (FileSystemAlreadyExistsException x) {
assertTrue(x.getMessage().contains("'foo'"));
}
```
After:
```
assertThatCode(() -> provider.newFileSystem(URI.create(pathUri)))
.as("filesystem created twice!") …
```
=> chore(test): Replace try/fail/catch/assert with assertThat

src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java
This PR extracts `supportedFileAttributeViews` into a static field so that the creation of the temporary `HashSet` and the call to `unmodifiable...` do not happen each time the method is called. It also uses just the supported value instead of having a size of `2`.
=> chore(S3FS): Extract supported file attribute views to static field

build.gradle, src/examples/java/software/amazon/nio/spi/examples/ListPrefix.java, src/examples/java/software/amazon/nio/spi/examples/Main.java, src/examples/java/software/amazon/nio/spi/examples/WalkFromRoot.java
This PR moves the example classes into their own `SourceSet` in order to reduce the amount of classes shipped with the library jar and it's size. As additional benefit, code coverage is not affected by those classes.
=> chore(examples): Move examples to their own `SourceSet`

src/main/java/software/amazon/nio/spi/s3/S3WritableByteChannel.java
*Issue #194:*
[S3WritableByteChannel does not consider contentType while putting an object into the bucket](https://github.com/awslabs/aws-java-nio-spi-for-s3/issues/194)
Upon putting an object into the S3 bucket (for instance, while copying), we need to also provide the content-type of the file. This could come crucial in cases like when the uploaded file (let's say an XML file) is going to be used by a specific application later.
While checking the implementation of `PutObjectRequest`, I didn't fine anywhere that `contentType` acquires a default value, so if `Files::probeContentType` returns a null value, it is the same as not calling the builder method. Hence I don't see any negative side-effects with this change.
By submitting this pull request, I confirm …
=> Provide content-type while putting object to S3

src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/main/java/software/amazon/nio/spi/s3/S3Path.java
Considering that in many places a check is done to verify the `path` (from the nio public API signature) is an `S3Path`, the changes introduce a method `checkPath` to avoid repetition of the code, better reusability and consistency (checks were done differently depending on the method).
The implementation is quite similar to the one used in `UnixFileSystemProvider` which is quite straight forward, replacing the path implementation with `S3Path`:
```
UnixPath checkPath(Path obj) {
if (obj == null)
throw new NullPointerException();
if (!(obj instanceof UnixPath))
throw new ProviderMismatchException();
return (UnixPath)obj;
}
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
=> chore: extract method to check Path is S3Path

build.gradle
Fixes https://github.com/awslabs/aws-java-nio-spi-for-s3/pull/223#pullrequestreview-1699625620. It is related to https://github.com/awslabs/aws-java-nio-spi-for-s3/pull/202, the `examples` sourceset was missing the `project` dependency.
*Another topic*
Something that was found out while running the examples is that jvm 11 is required due to the version of `logback`. Running with java 8 results in:
```
Caused by: java.lang.UnsupportedClassVersionError: ch/qos/logback/classic/spi/LogbackServiceProvider has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
According to [logback page](https://logback.qos.ch/dependencies.html), version 1.3 supports …
=> fix(examples): Add `project` to `examples` dependencies

src/examples/java/software/amazon/nio/spi/examples/ListPrefix.java, src/examples/java/software/amazon/nio/spi/examples/WalkFromRoot.java
#230 
Update examples to use standard nio patterns.
Use try with resources.
Use Collections.emptyMap() to make generics implicit.
=> use standard nio patterns

src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java
Fix a couple of javadoc warnings:
```
.../aws-java-nio-spi-for-s3/src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java:139: warning: no @param for <T>
public <T extends AwsClient> T universalClient(boolean async) {
^
.../aws-java-nio-spi-for-s3/src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java:587: warning: no description for @param
* @param <V>
^
2 warnings
```
=> javadoc: fix no @param (description) for <T>

README.md, build.gradle, src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java, src/main/java/software/amazon/nio/spi/s3/config/S3NioSpiConfiguration.java, src/main/java/software/amazon/nio/spi/s3/util/StringUtils.java
Compile and target jvm >= 11 for version 2.x according to https://github.com/awslabs/aws-java-nio-spi-for-s3/pull/228#issuecomment-1781633832.
=> build(java): Upgrade to java 11

.github/workflows/gradle.yml, .gitignore, CONTRIBUTING.md, THIRD-PARTY, build.gradle
As mentioned in https://github.com/awslabs/aws-java-nio-spi-for-s3/pull/223#issuecomment-1778739120:
This PR adds the [revapi](https://github.com/palantir/gradle-revapi) gradle plugin so that [API/ABI compatibility](https://blog.palantir.com/preventing-java-api-abi-breaks-with-gradle-revapi-c03cbdb0e940) is checked during the build (more specifically during `./gradlew check`). Whenever changes are introduced, the plugin verifies against the latest version (currently 1.2.4) and fails the build in case the are API/ABI incompatibilities. Breaking changes _can_ be accepted as documented in the Contribution guide.
Since there are many breaking changes for v2, they are currently accepted in the CI build. Once v2 is released, it the check on CI build should be commented …
=> build(revapi): Verify API/ABI compatibility during build

build.gradle, src/test/java/software/amazon/nio/spi/s3/S3ClientProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemTest.java, src/test/java/software/amazon/nio/spi/s3/S3Matchers.java, src/test/java/software/amazon/nio/spi/s3/S3PathTest.java, src/test/java/software/amazon/nio/spi/s3/S3ReadAheadByteChannelTest.java, src/test/java/software/amazon/nio/spi/s3/S3SeekableByteChannelTest.java, src/test/java/software/amazon/nio/spi/s3/config/S3NioSpiConfigurationTest.java
This PR enables Xlint checks during build; those warnings can reveal possible bugs, improper types or just add noise. With it enabled, ~53 warnings were found in the test sources. Those are also addressed in here
=> Show xlint warnings and some fixes

src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java, src/test/java/software/amazon/nio/spi/s3/FixedS3ClientProvider.java, src/test/java/software/amazon/nio/spi/s3/S3ClientProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemTest.java
The `generateClient` (and `generateAsyncClient`) method was quite complex, had several nested blocks (if/try/if/try/if). Some new methods have been extracted in order to make the code more readable and maintainable.
Both `generateClient` and `generateAsyncClient` shared the same logic - except for the underlying client that was generated. A new method `getClientForBucket` has been extracted that receives a function to construct the client for the given bucket location. The _old_ `generateClient` has been renamed to `generateSyncClient`.
=> refactor(S3ClientProvider): Reduce complexity of `generateClient`

src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/main/java/software/amazon/nio/spi/s3/S3Path.java, src/main/java/software/amazon/nio/spi/s3/S3ReadAheadByteChannel.java, src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3ClientProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java
This PR addresses some suggestions of the IDE:
* Unnecessary types
* Unnecessary variable initialization
* Replace one liner lambdas with expression lambdas
* Declared exceptions that are not thrown
* Replace `assertTrue(x instanceof b)` with `assertThat().isInstanceOf`
* Use collection.isEmpty() when possible
For the cases where `Unnecessary variable initialization` was found, the code has been rewritten with smaller methods, making the code easier to understand (see 2da3ec0f81e5ebe56c725d63ff03e07d06881af9 for example)
=> Improve maintainability / readability / javadoc

src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java
Since there are two schemes `s3` and `s3x`, it is convenient that the logs reflect the proper scheme.
=> log(S3FileSystem): Use scheme of the provider instead of `s3`

src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java
The call to get the "file" size in `S3SeekableByteChannel` is replaced with `S3BasicFileAttributes.size()` since it already provides a way to get a "file" size.
_Package Coverage_ (Before / After)
_Class Coverage_ (Before / After)
=> rewrite(S3SeekableByteChannel): Use `S3BasicFileAttributes` to get "file"size of path

src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java
* Extracts logic from long method
* Ensures use of try with resource for autoclosable filesystem.
* Improve exception handling
* Javadoc improvement
=> [chore] code inspection improvements

src/test/java/software/amazon/nio/spi/s3/S3FileSystemTest.java
This test in it's current form will only succeed if not credentials are set in the test environment. If there are credentials set then it will make a call to S3 which is not desirable in a test suite.
=> Remove test that requires call to S3 API not just client.

src/integrationTest/java/software/amazon/nio/spi/s3/Containers.java, src/integrationTest/java/software/amazon/nio/spi/s3/FilesCopyTest.java, src/integrationTest/java/software/amazon/nio/spi/s3/FilesReadTest.java, src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java, src/main/java/software/amazon/nio/spi/s3/S3ReadAheadByteChannel.java, src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java, src/main/java/software/amazon/nio/spi/s3/config/S3NioSpiConfiguration.java, src/test/java/software/amazon/nio/spi/s3/FixedS3ClientProvider.java, src/test/java/software/amazon/nio/spi/s3/S3ClientProviderTest.java
Issue #236 
As discussed in the issue, a `non-crt` asyncclient will be used for reading files through the `S3ReadAheadByteChannel`. This is the class used when using the nio api via `Files.copy` or `Files.read*`.
Some private methods have been renamed to better reflect the purpose of them.
=> test(Files): Add integration tests for Files.copy / read*

README.md, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java
#209
Document how we perform copy operations on directories.
=> document copy operation with respect to directories.

README.md
=> [chore] fix typo

src/main/java/software/amazon/nio/spi/s3/S3BasicFileAttributes.java, src/test/java/software/amazon/nio/spi/s3/S3BasicFileAttributesTest.java
A new `getObjectMetadata` method has been extracted from `S3BasicFileAttributes` in order to reuse it in `lastModifiedTime()`, `size()`, and `fileKey()`. Unit tests for the class have also been added for the cases when the path is a regular file or a directory.
Previous coverage:
Current coverage:
=> refactor(S3BasicFileAttributes): Extract and reuse `getObjectMetadata` method

src/main/java/software/amazon/nio/spi/s3/util/S3FileSystemInfo.java
Use `<br>` for line breaks.
Create hyperlinks
=> chore: java doc improvements

src/test/java/software/amazon/nio/spi/s3/util/S3FileSystemInfoTest.java, src/test/java/software/amazon/nio/spi/s3/util/S3XFileSystemInfoTest.java
#284 
I may have missed it in previous PRs. I also fixed a couple of headers.
=> fix for #284 - Missing S3FileSystemInfoTest.java

src/main/java/software/amazon/nio/spi/s3/S3BasicFileAttributeView.java, src/main/java/software/amazon/nio/spi/s3/S3BasicFileAttributes.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3BasicFileAttributesTest.java
The PR introduces a test for `S3BasicFileAttributes`, _when a timeout happens getting attributes of a regular file, an Exception should be thrown_. In order to achieve this, and avoid having to wait 1 minute( the _current_ default ) for the test to fail, the timeout is now configurable.
Coverage:
By the way, isn't 1 minute to high for a timeout? I imagine a user waiting up to 1 minute to get the size of a file would be too much and a bad user experience. I was thinking maybe 10 seconds would be a more sensible default. What are your thoughts @markjschreiber ?
=> test(S3BasicFileAttributes): When a timeout happens getting attributes of a regular file, an Exception should be thrown

src/main/java/software/amazon/nio/spi/s3/S3BasicFileAttributes.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java
The rewrite unifies the `return`s from `readAttributes` taking advantage of the filter option. As a consequence, `asMap()` method from `S3BasicFileAttributes` is not used anymore, so it has been cleaned up.
=> rewrite(S3FileSystemProvider): instantiate S3FileAttributes once

README.md
Since the old implementation was removed, a cleanup of the information on the README was needed
=> docs(README): Remove information about newFileSystem

src/integrationTest/java/software/amazon/nio/spi/s3/FilesDirectoryStreamTest.java, src/main/java/software/amazon/nio/spi/s3/S3DirectoryStream.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java
This PR brings changes to `S3FileSystemProvider`:
* extract methods to improve readability
* remove nested try / try statements
* reuse transfermanager to copy files
* extract new `S3DirectoryStream`
* a couple of changes with the `Flowable` transformation
* small rewrite of unit tests
* integration test for `should throw NoSuchFileException when bucket not found`
Coverage:
=> Maintenance S3FileSystemProvider

src/main/java/software/amazon/nio/spi/s3/S3BasicFileAttributeView.java, src/main/java/software/amazon/nio/spi/s3/S3BasicFileAttributes.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3BasicFileAttributesTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3SeekableByteChannelTest.java
The implementation of S3BasicFileAttributes does IO whenever `size()`, `lastModified()` or `fileKey()` are invoked. When there are network problems, `RuntimeException`s are thrown, since the `BasicFileAttributes` *nio* interface does not declare any expected exceptions to be thrown when calling these methods.
In order to conform better with the contract specified by the *nio* interfaces, the IO done in `size()`, `lastModified()` and `fileKey()` methods is now done before constructing the attributes: when `readAttributes` from the *provider* or the *attributeview* is called. `readAttributes` in those interfaces specify that it can throw `IOException` and therefore seems a better place where to do the IO to get the object metadata.
As a side effect, requests to S3 …
=> chore(S3BasicFileAttributes): Do IO in methods that throw `IOException`

src/examples/java/software/amazon/nio/spi/examples/MoveObject.java, src/main/java/software/amazon/nio/spi/s3/S3BasicFileAttributeView.java, src/test/java/software/amazon/nio/spi/s3/S3BasicFileAttributeViewTest.java
#339 
Remove exception when attempting to set times. Times are not modified because this isn't supported on S3.
=> no longer throw exception on set times

src/main/java/software/amazon/nio/spi/s3/S3Path.java, src/test/java/software/amazon/nio/spi/s3/S3PathTest.java
#293 
The current implementation violates the intended behaviour or relativize when relativizing a path to the root. The correct behaviour should be like:
```
Path root = FileSystems.getDefault().getRootDirectories().iterator().next();
Path path = FileSystems.getDefault().getPath("/a/b");
Path relative = root.relativize(path); // -> a/b, isAbsolute() == false
```
Side note: the use of var is particularly disappointing in `S3Path` where it should be clear if an object is a `Path` or a `S3Path`
=> fix for #293

.github/workflows/gradle.yml
=> chore: Update github actions as Node 16 is deprecated.

src/main/java/software/amazon/nio/spi/s3/S3Path.java, src/test/java/software/amazon/nio/spi/s3/S3PathTest.java
#292 
keeps absolute paths absolute following normalization
=> fix: normalize keeps absolute paths absolute

src/main/java/software/amazon/nio/spi/s3/S3ReadAheadByteChannel.java, src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3SeekableByteChannelTest.java
#191 
Fixes #191 
Feeds configuration through to the creation of the `S3ByteChannel` and the read ahead delegate. Adds test to demonstrate configuration is used.
=> fix: use environment configuration when creating a byte channel

README.md
Issue #109 
Add note on README to document how to avoid importing uber jar for `crt` client and importing only a platform-specific jar.
| Content of uber jar | Content of platform-specific jar |
|--------|--------|
| ![Screenshot 2024-03-18 204137](https://github.com/awslabs/aws-java-nio-spi-for-s3/assets/283778/74d24352-63d2-4af6-b9d1-8cb6df4250f5) | ![Screenshot 2024-03-18 204527](https://github.com/awslabs/aws-java-nio-spi-for-s3/assets/283778/6bb3f326-a124-4191-b821-ebe8da44c3f0) |
=> docs(README): Add "how to" reduce library dependencies

README.md
Update readme to use the coordinates for the latest version (2.0.0)
@markjschreiber There are references to `build/libs/nio-spi-for-s3-1.1.0-all.jar`, are those published to maven repository? Do they need to be updated as well?
=> chore(README): Update coordinates to latest version

.github/workflows/gradle.yml, .gitignore
Now that all breaking changes for v2 are done, there is no need to continue accepting breaking changes in API/ABI.
Reference for [RevApi](https://revapi.org/revapi-java/0.28.1/index.html)
=> build(ci): Remove `revapiAcceptAllBreaks` on revapi

src/test/java/software/amazon/nio/spi/s3/S3WritableByteChannelTest.java
#432 
fix for #432 Build broken with JDK 21
=> fixed #432 Build broken with JDK 21

src/main/java/software/amazon/nio/spi/s3/S3WritableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3WritableByteChannelTest.java
*Issue #, if available:* #453
Added a check in the `S3WritableByteChannel#close` method to prevent another upload attempt.
=> fix: close() call on already closed S3WritableByteChannel (awslabs#453)

.gitignore
Adds `.palantir` directory to gitignore
=> chore: ignores directory used to check for breaking API changes.

src/examples/java/software/amazon/nio/spi/examples/MoveDirectory.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java
#430 
Fixes #430 by ensuring that all code considers `/foo/bar/` to be a directory and `/foo/baa` to be an object (file) in accordance with the behavior of S3.
=> fix: resolves issues when copying or moving objects via`Files` class

src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java, src/test/java/software/amazon/nio/spi/s3/S3ClientProviderTest.java
#443 
Changes the strategy to discover bucket location to prefer the region of the current profile or machine. Now the order is:
1. Attempt to head the bucket with a client from the current region
2. If the attempt receives a `301` redirect then obtain the region from there
3. For other errors (like `403` forbidden) attempt to call the soon to be deprecated `GetBucketLocation` S3 API.
=> fix: changes strategy to discover bucket location to prefer the region of the current profile or machine

src/examples/java/software/amazon/nio/spi/examples/CreateBucket.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java
exceptions as `FileSystemAlreadyExists` exception
#461
Fixes #461 by rethrowing `BucketAlreadyExistsException` and `BucketAlreadyOwnedException` as `FileSystemAlreadyExists` exception.
=> fix: rethrows `BucketAlreadyExists` and `BucketAlreadyOwned` 

src/examples/java/software/amazon/nio/spi/examples/CreateBucket.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/test/java/software/amazon/nio/spi/s3/S3BasicFileAttributeViewTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemTest.java, src/test/java/software/amazon/nio/spi/s3/S3PathTest.java, src/test/java/software/amazon/nio/spi/s3/S3ReadAheadByteChannelTest.java, src/test/java/software/amazon/nio/spi/s3/S3SeekableByteChannelTest.java, src/test/java/software/amazon/nio/spi/s3/S3XFileSystemProviderTest.java
#460 
removed redundant boolean flag in `newFileSystem(URI)` call as it should always be true.
=> fix: for issue #460

src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java
461
Improves previous fix by adding the causal exception so that users can better distinguish between bucket exists and already owned by the user vs. bucket already exists (owned by someone else).
=> fix: adds causal exception

src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java
No issue created this time. If needed, I can create one later.
Observed when trying to use JDK's `Files.move()` method. This method uses the `java.nio.file.CopyMoveHelper#copyToForeignTarget` method. The implementation tries to get the `PosixFileAttributeView` (in line 109). This fails for the S3 implementation with an `UnsupportedOperationException`, which is not caught by JDK's code, resulting in the move operation to fail.
Having read the method description, I'm of the opinion that the method should return `null` in case of an unsupported view type. This would at least be compliant with the method comment in the `copyToForeignTarget` method (line 108):
> // retrieve source posix view, null if unsupported
I've adapted the test …
=> fix: Let getFileAttributeView() return null for unsupported view class.

src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java
Fixes #497
The copy and delete code was currently treating `/foo/` and `/foo` as a directory, which in the S3 context is incorrect (as perfectly summed up [here](https://github.com/awslabs/aws-java-nio-spi-for-s3/blob/01542979007859a51adfcc0aef9338e8a4fa4ade/src/main/java/software/amazon/nio/spi/s3/PosixLikePathRepresentation.java#L146)). If the given path is not a directory, it should not be listing objects from S3 and returning all those that match the prefix. Rather, it should just be performing the copy/delete operation on that given object. This change adds a check for whether the given source is a directory and acts accordingly.
=> Correctly handle copy and delete operations on single objects

src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java
Fixes #494
Pulls the client instantiation out of the `try-with-resource` block to stop it being closed and therefore not usable when refreshing expired credentials.
=> fix: fixes refreshing expired credentials by preventing DefaultCredentialsProvider from being autoclosed

src/main/java/software/amazon/nio/spi/s3/S3ClientProvider.java, src/test/java/software/amazon/nio/spi/s3/FixedS3ClientProvider.java, src/test/java/software/amazon/nio/spi/s3/S3ClientProviderTest.java
#555 
removes custom bucket region discovery in favor of creating cross region clients now available in the SDK.
=> (refactor) delegates cross region bucket location determination to SDK

src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java, src/main/java/software/amazon/nio/spi/s3/S3Path.java, src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3BasicFileAttributesTest.java, src/test/java/software/amazon/nio/spi/s3/S3SeekableByteChannelTest.java, src/test/java/software/amazon/nio/spi/s3/S3XFileSystemProviderTest.java
This is a partial fix for issue #601.
=> fix: S3FileSystem configuration visibility and name update

src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java
This is an intermediate 'fix' for issue #597 until API breaking changes are possible.
=> fix: deprecated the configuration field and setter

src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java
The documentation states "May be null or empty." but that was clearly not the case.
Added a test for the fix which expects call to not fail with anything but an `IOException`.
=> fix: made S3FileSystemProvider#newFileSystem better match its documentation

src/integrationTest/java/software/amazon/nio/spi/s3/FileChannelOpenTest.java, src/integrationTest/java/software/amazon/nio/spi/s3/FilesNewByteChannelTest.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystemProvider.java, src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java, src/main/java/software/amazon/nio/spi/s3/S3WritableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3SeekableByteChannelTest.java, src/test/java/software/amazon/nio/spi/s3/S3WritableByteChannelTest.java
- Enable simultaneous `READ` and `WRITE` support when opening a `SeekableByteChannel` (or `FileChannel`).
- Enable random access to the temporarily cached S3 file, so that we can seek to a particular position, and read from or write to that.
=> Enable random access when opening a `SeekableByteChannel` or `FileChannel`

build.gradle
To match the JUnit Jupiter version used by `mockito-junit-jupiter` we should set the JUnit Jupiter of this project to `5.11.4`. Additionally, the logging implementation `logback-classic` is set to `runtimeOnly` scope (for tests), because no one should use the code directly while writing tests.
=> Update JUnit Jupiter to 5.11.4

src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java, src/main/java/software/amazon/nio/spi/s3/S3WritableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemTest.java, src/test/java/software/amazon/nio/spi/s3/S3WritableByteChannelTest.java
To be able to better understand which file I'm messing around with while debugging locally, I find it really helpful when the directory structure is preserved as it exists on S3. Therefore, I suggest to have a temporary directory per `S3FileSystem` instance and locally cached S3 files are mirrored there with their key in correspondence to the bucket location.
=> Use a temporary directory per file system and preserve the directory structure locally

src/integrationTest/java/software/amazon/nio/spi/s3/Containers.java, src/integrationTest/java/software/amazon/nio/spi/s3/FilesNewByteChannelTest.java, src/main/java/software/amazon/nio/spi/s3/S3OpenOption.java, src/main/java/software/amazon/nio/spi/s3/S3RangeHeader.java, src/main/java/software/amazon/nio/spi/s3/S3TransferUtil.java, src/main/java/software/amazon/nio/spi/s3/S3WritableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3SeekableByteChannelTest.java, src/test/java/software/amazon/nio/spi/s3/S3TransferUtilTest.java, src/test/java/software/amazon/nio/spi/s3/S3WritableByteChannelTest.java
I want to partially get an S3 object when opening a `SeekableByteChannel` or `FileChannel`. When a HTTP `Range` header is specified the HEAD object request is omitted.
=> Provide S3 specific `OpenOption` to add a HTTP `Range` header

src/main/java/software/amazon/nio/spi/s3/S3TransferUtil.java, src/main/java/software/amazon/nio/spi/s3/S3WritableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3TransferUtilTest.java, src/test/java/software/amazon/nio/spi/s3/S3WritableByteChannelTest.java
An exception while downloading from S3 or uploading to S3 is not traceable to the caller, because it is created in another thread. To make it traceable, we need to propagate the exception from the the caller side (e.g. `S3TransferUtil`).
=> Improve exception handling on download/upload

src/integrationTest/java/software/amazon/nio/spi/s3/FilesCopyTest.java, src/main/java/software/amazon/nio/spi/s3/S3BasicFileAttributes.java, src/test/java/software/amazon/nio/spi/s3/S3BasicFileAttributesTest.java
When copying a non-existent S3 object, a `NoSuchFileException` should be thrown. This would make it easier for the caller to handle this case explicitly.
=> Throw `NoSuchFileException` when copying a non-existent file

src/integrationTest/java/software/amazon/nio/spi/s3/FileChannelOpenTest.java, src/integrationTest/java/software/amazon/nio/spi/s3/FilesNewByteChannelTest.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java, src/main/java/software/amazon/nio/spi/s3/S3OpenOption.java, src/main/java/software/amazon/nio/spi/s3/S3PreventConcurrentOverwrite.java, src/main/java/software/amazon/nio/spi/s3/S3RangeHeader.java, src/main/java/software/amazon/nio/spi/s3/S3TransferUtil.java, src/main/java/software/amazon/nio/spi/s3/S3WritableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3FileSystemTest.java, src/test/java/software/amazon/nio/spi/s3/S3PreventConcurrentOverwriteTest.java, src/test/java/software/amazon/nio/spi/s3/S3TransferUtilTest.java, src/test/java/software/amazon/nio/spi/s3/S3WritableByteChannelTest.java
We want to prevent overwrites if the S3 object has changed in the meantime. For this we utilize an `OpenOption` that captures the `ETag` on `GetObject` and sets the `If-Match` header on `PutObject`. When opening a `FileChannel` or `SeekableByteChannel`, the ETag is stored in a field and when closing the channel (or while calling `FileChannel.force`) the stored ETag is set as `If-Match` header on the corresponding `PutObjectRequest`. This prevents overwriting of the S3 object between opening and closing the channel.
Additionally, this change fixes the ability to open multiple channels on the same S3 object.
=> Prevent concurrent overwrites of an S3 object

src/test/java/software/amazon/nio/spi/s3/S3FileSystemProviderTest.java
addsFileSystemAlreadyExistsException as option for newFileSystemUri test
=> addsFileSystemAlreadyExistsException as option for newFileSystemUri test

src/integrationTest/java/software/amazon/nio/spi/s3/FileChannelOpenTest.java, src/integrationTest/java/software/amazon/nio/spi/s3/FilesNewByteChannelTest.java, src/main/java/software/amazon/nio/spi/s3/S3OpenOption.java, src/main/java/software/amazon/nio/spi/s3/S3TransferException.java, src/main/java/software/amazon/nio/spi/s3/S3TransferUtil.java, src/test/java/software/amazon/nio/spi/s3/S3TransferExceptionTest.java, src/test/java/software/amazon/nio/spi/s3/S3TransferUtilTest.java, src/test/java/software/amazon/nio/spi/s3/S3WritableByteChannelTest.java
If we want to re-apply changes on a `FileChannel` or `SeekableByteChannel` that failed to upload due to failing preconditions, we need to figure out if the resulting failure was a `PreconditionFailed`. To figure this out, we would need to parse the stacktrace, the causes and their message. To avoid that, we need a custom `IOException` that enable us to check the status code or error code from the causing `AwsServiceException`.
=> Provide a dedicated `IOException` to handle expected failures

src/integrationTest/java/software/amazon/nio/spi/s3/FileChannelOpenTest.java, src/integrationTest/java/software/amazon/nio/spi/s3/FilesNewByteChannelTest.java, src/main/java/software/amazon/nio/spi/s3/Crc32FileIntegrityCheck.java, src/main/java/software/amazon/nio/spi/s3/Crc32cFileIntegrityCheck.java, src/main/java/software/amazon/nio/spi/s3/Crc64nvmeFileIntegrityCheck.java, src/main/java/software/amazon/nio/spi/s3/S3FileSystem.java, src/main/java/software/amazon/nio/spi/s3/S3OpenOption.java, src/main/java/software/amazon/nio/spi/s3/S3PreventConcurrentOverwrite.java, src/main/java/software/amazon/nio/spi/s3/S3PutOnlyIfModified.java, src/main/java/software/amazon/nio/spi/s3/S3RangeHeader.java, src/main/java/software/amazon/nio/spi/s3/S3SeekableByteChannel.java, src/main/java/software/amazon/nio/spi/s3/S3TransferUtil.java, src/main/java/software/amazon/nio/spi/s3/S3UseTransferManager.java, src/main/java/software/amazon/nio/spi/s3/S3WritableByteChannel.java, src/main/java/software/amazon/nio/spi/s3/config/S3NioSpiConfiguration.java, src/test/java/software/amazon/nio/spi/s3/S3OpenOptionTest.java, src/test/java/software/amazon/nio/spi/s3/S3TransferUtilTest.java, src/test/java/software/amazon/nio/spi/s3/config/S3NioSpiConfigurationTest.java
The `S3TransferManager` is particularly good for large S3 objects that are to be downloaded from AWS S3 or uploaded to AWS S3. If the S3 objects are small, it is sufficient to do plain `GetObject` or `PutObject` requests. When setting the HTTP `Range` header on an `GetObjectRequest`, e.g. by setting the open option`S3OpenOption.range(start, end)`, the `HeadRequest` can be avoided and thus the latency can be reduced while opening a `FileChannel` or `SeekableByteChannel`. When the `S3TransferManager` is used, the `HeadRequest` will always be performed on download no matter if a `Range` header is present.
By default, the `S3TransferManager` is enabled. But the users of this library can change the defaults. To make this possible, we introduced a method to programmatically change the default …
=> Use the 'S3TransferManager' by default, but allow users to disable it

src/integrationTest/java/software/amazon/nio/spi/s3/FilesNewByteChannelTest.java, src/main/java/software/amazon/nio/spi/s3/S3AssumeObjectNotExists.java, src/main/java/software/amazon/nio/spi/s3/S3OpenOption.java, src/main/java/software/amazon/nio/spi/s3/S3WritableByteChannel.java, src/test/java/software/amazon/nio/spi/s3/S3PreventOverwriteIfExistsTest.java, src/test/java/software/amazon/nio/spi/s3/S3WritableByteChannelTest.java
I want to prevent myself from accidentally overwriting existing S3 objects, especially in a scenario where only new objects should be created.
With this change, we introduce a new `OpenOption` that prevents overwriting an existing object by applying an HTTP `If-None-Match=*` header to the corresponding `PutObjectRequest` when closing the underlying `SeekableByteChannel`. Additionally, if this new option is present, no download attempt is made to reduce latency.
=> Add option to prevent an existing S3 object from being overwritten
